### ISSUE TITLE
Error running cdp test suite

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdp#43]
```
/Users/doutriaux1/anaconda2/envs/pmp/lib/python3.6/site-packages/dask/context.py:23: UserWarning: The dask.set_options function has been deprecated. Please use dask.config.set instead
  warnings.warn("The dask.set_options function has been deprecated. "
Traceback (most recent call last):
  File "/Users/doutriaux1/anaconda2/envs/pmp/bin/computeStdDailyMeansWrapped.py", line 151, in <module>
    cdp.cdp_run.multiprocess(compute, params, num_workers=args.num_workers)
  File "/Users/doutriaux1/anaconda2/envs/pmp/lib/python3.6/site-packages/cdp/cdp_run.py", line 22, in multiprocess
    elif hasattr(parameters[0], 'num_workers'):
IndexError: list index out of range
```

**Comment by doutriaux1** [comment]
to get the error run (on pmp master)
```
computeStdDailyMeansWrapped.py --mp test_data --rd test_data/results/nc -t "sample_data_pr_%(model).nc" -m7
```

**Comment by doutriaux1** [comment]
running:
```
computeStdDailyMeansWrapped.py --mp test_data --rd test_data/results/nc -t "sample_data_pr_%(model).nc" -m7 -n 2
```

Leads to:
```
SKIPPING: []
FILES: []
PARAMS: []
/Users/doutriaux1/anaconda2/envs/pmp/lib/python3.6/site-packages/dask/context.py:23: UserWarning: The dask.set_options function has been deprecated. Please use dask.config.set instead
  warnings.warn("The dask.set_options function has been deprecated. "
/Users/doutriaux1/anaconda2/envs/pmp/lib/python3.6/site-packages/dask/base.py:828: UserWarning: The get= keyword has been deprecated. Please use the scheduler= keyword instead with the name of the desired scheduler like 'threads' or 'processes'
  warnings.warn("The get= keyword has been deprecated. "
```
